backend:
  name: git-gateway
  branch: main
collections:
  - name: posts
    label: Blog Posts
    folder: blog/posts
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Body, name: body, widget: markdown}